import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'ChatApp, Talk with the world !',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-h-[100vh] max-h-[100vh] box-border bg-slate-950 flex flex-col items-center justify-center text-black'>
        {children}
      </body>
    </html>
  )
}
